mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com/example/hotel/entity
  configuration:
    map-underscore-to-camel-case: false  # 关闭自动驼峰命名映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:sqlserver://localhost:1433;DatabaseName=hotel;encrypt=false
    username: sa
    password: 282310
  application:
    name: microservice-provider
  jackson:
    # 返回格式化日期
    date-format: yyyy-MM-dd HH:mm:ss #设置全局的日期格式为年月日时分秒
    time-zone: GMT+8 #世界标准时间,为了方式时差,需要+8小时
  mvc:
    # 前端参数格式化
    #    format:
    #      # String格式化日期
    #      date: yyyy-MM-dd HH:mm:ss
    pathmatch:
      matching-strategy: ant_path_matcher

file-save-path: D:/Pictures/img/
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8